UNWIND range(1, 100) AS i
CREATE (e:Ejercicio {
    nombre: CASE 
        WHEN i <= 10 THEN ["Flexiones", "Sentadillas", "Dominadas", "Burpees", "Plancha", "Zancadas", "Abdominales", "Fondos", "Elevación de talones", "Puente de glúteos"][i - 1]
        WHEN i <= 20 THEN ["Press de banca", "Remo con barra", "Peso muerto", "Curl de bíceps", "Extensión de tríceps", "Sentadillas con barra", "Press militar", "Dominadas con peso", "Tijeras", "Plancha lateral"][i - 11]
        WHEN i <= 30 THEN ["Crunches", "Flexiones con rodillas", "Sentadillas sumo", "Zancadas laterales", "Kettlebell swings", "Tijeras verticales", "Elevación de piernas", "Plancha con levantamiento de pierna", "Burpees con salto", "Flexiones de tríceps"][i - 21]
        WHEN i <= 40 THEN ["Remo con mancuerna", "Sentadillas con kettlebell", "Push press", "Abdominales con giro", "Flexiones con aplauso", "Zancadas con salto", "Remo invertido", "Curl de pierna", "Extensión de cadera", "Prensa de piernas"][i - 31]
        WHEN i <= 50 THEN ["Plancha con rodillas", "Flexiones de pike", "Flexiones de antebrazo", "Elevaciones de talón en máquina", "Crunches inversos", "Sentadillas búlgaras", "Push-ups en TRX", "Plancha con toque de hombro", "Sentadillas con salto", "Flexiones con agarre cerrado"][i - 41]
        WHEN i <= 60 THEN ["Remo con banda elástica", "Curl de bíceps en banco inclinado", "Estocadas hacia adelante", "Flexiones de codo en paralelas", "Crunches con balón medicinal", "Sentadillas con mancuernas", "Plancha con elevación de brazo", "Tijeras con peso", "Extensión de tríceps con cuerda", "Flexiones con pies elevados"][i - 51]
        WHEN i <= 70 THEN ["Elevaciones de piernas colgado", "Flexiones con agarre ancho", "Zancadas con mancuernas", "Abdominales en máquina", "Remo con banda", "Prensa de hombros", "Sentadillas en caja", "Plancha con levantamiento de cadera", "Flexiones con apoyo de rodillas", "Crunches con banda"][i - 61]
        WHEN i <= 80 THEN ["Flexiones de pectoral", "Curl de piernas en máquina", "Elevación de caderas en banco", "Plancha con desplazamiento", "Sentadillas con barra frontal", "Remo con kettlebell", "Crunches en fitball", "Extensión de piernas en máquina", "Flexiones con peso", "Elevaciones de pantorrillas"][i - 71]
        WHEN i <= 90 THEN ["Plancha con levantamiento de pierna alterno", "Sentadillas en máquina", "Flexiones en anillas", "Crunches en banco inclinado", "Zancadas en máquina", "Remo con barra T", "Plancha con toque de pie", "Flexiones de pecho en TRX", "Extensiones de tríceps en máquina", "Elevación de talones en prensa"][i - 81]
        ELSE ["Sentadillas con banda", "Flexiones de tríceps en banco", "Crunches con elevación de piernas", "Zancadas con barra", "Plancha con giro", "Flexiones con rodillas en fitball", "Sentadillas con kettlebell a una pierna", "Curl de bíceps con cuerda", "Elevación de cadera en fitball", "Flexiones de hombros con mancuernas"][i - 91]
    END,
    descripcion: CASE 
        WHEN i <= 10 THEN ["Ejercicio básico de fuerza para el pecho y brazos.", "Ejercicio para fortalecer las piernas y glúteos.", "Ejercicio para desarrollar la fuerza de la espalda y brazos.", "Ejercicio cardiovascular que combina fuerza y resistencia.", "Ejercicio isométrico para el core.", "Ejercicio para fortalecer piernas y mejorar equilibrio.", "Ejercicio abdominal clásico para fortalecer el core.", "Ejercicio para trabajar los tríceps y el pecho.", "Ejercicio para trabajar las pantorrillas.", "Ejercicio para fortalecer los glúteos y la zona lumbar."][i - 1]
        WHEN i <= 20 THEN ["Ejercicio de fuerza para el pecho y tríceps.", "Ejercicio para trabajar la espalda y mejorar la postura.", "Ejercicio compuesto para fortalecer la espalda baja y piernas.", "Ejercicio de aislamiento para los bíceps.", "Ejercicio de aislamiento para los tríceps.", "Ejercicio de fuerza para las piernas con peso.", "Ejercicio para desarrollar los hombros y el core.", "Ejercicio avanzado para espalda y brazos.", "Ejercicio de cardio y fuerza para piernas y glúteos.", "Ejercicio isométrico avanzado para trabajar el core y los oblicuos."][i - 11]
        WHEN i <= 30 THEN ["Ejercicio para fortalecer los músculos abdominales.", "Versión más sencilla de flexiones para principiantes.", "Variante de sentadillas para trabajar los abductores.", "Ejercicio de fuerza y equilibrio para las piernas.", "Ejercicio explosivo con pesas para fuerza y resistencia.", "Ejercicio para fortalecer los músculos abdominales y mejorar la coordinación.", "Ejercicio para desarrollar los músculos abdominales inferiores.", "Variante de plancha para trabajar el core y las piernas.", "Ejercicio avanzado para cardio y fuerza.", "Ejercicio para fortalecer los tríceps y el pecho."][i - 21]
        WHEN i <= 40 THEN ["Ejercicio para trabajar la espalda con peso libre.", "Variante de sentadillas para aumentar la fuerza con pesas kettlebell.", "Ejercicio para hombros que combina fuerza y explosividad.", "Ejercicio abdominal con rotación para trabajar los oblicuos.", "Flexiones dinámicas para mejorar la explosividad del tren superior.", "Zancadas avanzadas para fortalecer las piernas con salto.", "Ejercicio de fuerza para la espalda usando el peso corporal.", "Ejercicio de aislamiento para los isquiotibiales.", "Ejercicio para fortalecer los glúteos y la zona lumbar.", "Ejercicio de fuerza para las piernas con máquina."][i - 31] 
        WHEN i <= 50 THEN ["Variante de plancha que involucra las rodillas para mayor activación del core.", "Flexiones inclinadas para trabajar el core y los hombros.", "Flexiones con los antebrazos para fortalecer el core.", "Ejercicio de pantorrillas utilizando máquina para mayor resistencia.", "Ejercicio abdominal inverso para los músculos inferiores del core.", "Sentadillas asistidas que trabajan fuerza y equilibrio en una pierna.", "Ejercicio avanzado de push-ups en suspensión TRX.", "Variante de plancha para trabajar los hombros y la estabilidad.", "Sentadillas pliométricas para aumentar la fuerza y velocidad en las piernas.", "Flexiones con agarre cerrado para mayor trabajo en el tríceps."][i - 41] 
        WHEN i <= 60 THEN ["Ejercicio para trabajar la espalda con bandas de resistencia.", "Curl de bíceps con banco inclinado para un rango de movimiento completo.", "Ejercicio de estocadas para fortalecer las piernas y el equilibrio.", "Flexiones en paralelas para desarrollar el pecho y tríceps.", "Crunches con balón medicinal para mayor resistencia abdominal.", "Sentadillas con mancuernas para mejorar fuerza y estabilidad.", "Variante de plancha con elevación de brazo para fortalecer core y hombros.", "Ejercicio para piernas que combina tijeras y peso para mayor resistencia.", "Extensión de tríceps con cuerda para un rango de movimiento completo.", "Flexiones avanzadas con pies elevados para mayor trabajo en pecho y hombros."][i - 51] 
        WHEN i <= 70 THEN ["Elevación avanzada de piernas colgado para fortalecer el core.", "Variante de flexiones con mayor amplitud para trabajar el pecho y la espalda.", "Zancadas con mancuernas para mejorar la fuerza de las piernas.", "Abdominales en máquina para mayor intensidad en el core.", "Remo con banda elástica para trabajar la espalda y estabilidad.", "Ejercicio para los hombros que mejora la fuerza en prensas.", "Sentadillas en caja para mejorar el control y la explosividad.", "Variante de plancha con elevación de cadera para trabajar glúteos y core.", "Flexiones asistidas con rodillas para principiantes.", "Crunches con banda elástica para mayor resistencia en el core."][i - 61] 
        WHEN i <= 80 THEN ["Flexiones para trabajar intensamente el pecho y el tren superior.", "Ejercicio de curl de piernas en máquina para fortalecer los isquiotibiales.", "Elevación de caderas en banco para trabajar glúteos y zona lumbar.", "Plancha dinámica con desplazamiento para mejorar la coordinación y el core.", "Sentadillas con barra frontal para fortalecer el core y las piernas.", "Remo con kettlebell para mejorar la fuerza y estabilidad en la espalda.", "Crunches en fitball para fortalecer el core y mejorar el equilibrio.", "Extensión de piernas en máquina para trabajar los cuádriceps.", "Flexiones con peso adicional para aumentar la resistencia y fortalecer pecho y tríceps.", "Elevaciones de pantorrillas para trabajar los gemelos."][i - 71] 
        WHEN i <= 90 THEN ["Variante avanzada de plancha que involucra el levantamiento alterno de piernas.", "Sentadillas en máquina para trabajar la fuerza de las piernas.", "Flexiones avanzadas en anillas para trabajar pecho, hombros y estabilidad.", "Crunches en banco inclinado para intensificar el trabajo abdominal.", "Zancadas asistidas en máquina para fortalecer las piernas.", "Remo con barra T para trabajar la espalda con intensidad.", "Plancha avanzada con toque de pie para mejorar la coordinación y el core.", "Flexiones en suspensión TRX para trabajar el pecho y la estabilidad.", "Extensión de tríceps en máquina para aislar y fortalecer el tríceps.", "Elevación de talones en prensa para fortalecer los gemelos."][i - 81] 
        ELSE ["Sentadillas asistidas con banda elástica para aumentar la resistencia.", "Flexiones de tríceps en banco para aislar el tríceps.", "Crunches con elevación de piernas para fortalecer el core.", "Zancadas con barra para trabajar fuerza y equilibrio en las piernas.", "Plancha con giro para trabajar los oblicuos.", "Flexiones avanzadas con rodillas apoyadas en fitball.", "Sentadillas con kettlebell a una pierna para trabajar equilibrio y fuerza.", "Curl de bíceps con cuerda para mayor resistencia.", "Elevación de caderas en fitball para fortalecer glúteos y core.", "Flexiones de hombros con mancuernas para trabajar la parte superior del cuerpo."][i - 91] 
    END, 
    esPorTiempo: CASE 
        WHEN i % 2 = 0 THEN true 
        ELSE false 
    END, 
    cantidadRepeticiones: CASE 
        WHEN i % 2 = 1 THEN toString(10 + i) 
        ELSE null 
    END, 
    cantidadTiempo: CASE 
        WHEN i % 2 = 0 THEN 30 + i 
        ELSE null 
    END 
    });
