version: '3.8'

services:  database:
    image: neo4j:5.23.0
    environment:
      - NEO4J_AUTH=neo4j/ericfaculucas
    ports:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - ../common/backend/m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports: